name: CI
on:
  push: { branches: [ main ] }
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5
    env:
      NODE_ENV: test
      BOT_TOKEN: "TEST_TOKEN"
      BASE_URL: "http://localhost:3000"
      WEBHOOK_PATH: "/bot/webhook"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/app"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run migrate
      - run: npm test
